# Development Environment Configuration
# Optimized for development and testing

config_version: "1.0.0"
environment: "development"

# Device Configuration
device:
  preferred_device: "auto"
  device_fallback_order: ["cuda", "mps", "cpu"]
  gpu_memory_fraction: 0.6  # Conservative for development
  enable_mixed_precision: false  # Disabled for debugging
  cpu_threads: null  # Auto-detect
  cpu_usage_threshold: 70.0
  cpu_critical_threshold: 85.0
  max_concurrent_processes: 2  # Lower for development
  cpu_concurrency_limit: 1
  gpu_concurrency_limit: 4

# Audio Processing
audio:
  sample_rate: 16000
  chunk_size: 4096
  segment_duration_s: 2.0
  n_mels: 80
  n_fft: 512
  hop_length: 160
  win_length: 400
  n_lfcc: 20
  overlap_ratio: 0.75
  preemphasis_coeff: 0.97
  min_duration_s: 0.1
  max_duration_s: 10.0  # Shorter for dev testing
  silence_threshold: 0.01

# Security and Resource Limits
security:
  max_memory_gb: 4.0  # Lower limit for development
  memory_warning_threshold_gb: 3.0
  enable_memory_monitoring: true
  max_processing_time_s: 120.0  # Shorter timeout for quick iteration
  model_load_timeout_s: 60.0
  inference_timeout_s: 30.0
  max_file_size_mb: 50.0  # Smaller files for testing
  max_filename_length: 255
  max_path_length: 260
  allowed_file_extensions: [".wav", ".mp3", ".flac", ".m4a", ".ogg"]
  enable_file_validation: true
  enable_path_traversal_protection: true
  quarantine_suspicious_files: true
  monitoring_interval_s: 2.0  # More frequent monitoring
  enable_resource_limiting: true

# Bayesian Configuration
bayesian:
  enable_temporal_modeling: true
  enable_hierarchical_modeling: true
  enable_causal_analysis: true
  inference_method: "variational"
  temporal_window_size: 5  # Smaller for faster processing
  max_temporal_history: 10
  prior_authentic_prob: 0.7
  uncertainty_threshold: 0.15  # Higher threshold for development
  confidence_threshold: 0.7
  delta_fr_low_threshold: 0.3
  delta_fr_high_threshold: 0.7
  delta_ft_low_threshold: 0.01
  delta_ft_high_threshold: 0.05
  delta_fv_low_threshold: 0.2
  delta_fv_high_threshold: 0.5
  user_weight: 0.3
  session_weight: 0.4
  audio_weight: 0.3
  user_adaptation_rate: 0.2  # Faster adaptation for testing
  min_samples_for_adaptation: 3
  session_timeout_s: 1800  # 30 minutes
  low_risk_threshold: 0.8
  medium_risk_threshold: 0.4
  same_state_prob: 0.7
  adjacent_state_prob: 0.25
  distant_state_prob: 0.05

# Feature Extraction
features:
  batch_size: 2  # Small batches for development
  enable_length_bucketing: true
  max_batch_duration_s: 30.0
  enable_hubert_features: true
  enable_mel_spectrogram: true
  enable_lfcc_features: true
  enable_physics_features: true
  embedding_dim_for_physics: 1024
  physics_window_size_ms: 100
  physics_overlap_ratio: 0.5
  max_rotation_angle_rad: 0.1
  vibration_amplitude_scale: 0.05
  enable_bessel_features: true
  max_pca_components: 8
  enable_feature_validation: true
  nan_handling_strategy: "replace"
  feature_normalization: true

# Paths
paths:
  data_dir: "data"
  results_dir: "results_dev"
  cache_dir: "cache_dev"
  logs_dir: "logs"
  models_dir: "models"
  quarantine_dir: "quarantine"
  results_filename_pattern: "dev_features_{timestamp}.csv"
  log_filename_pattern: "dev_deepfake_{date}.log"
  cache_filename_pattern: "dev_features_{hash}.pkl"
  create_dirs_if_missing: true
  dir_permissions: 0o755
  file_permissions: 0o644

# Model Configuration
models:
  hubert_model_path: "facebook/hubert-large-ls960-ft"
  hubert_processor_path: null
  local_models_dir: "models"
  enable_model_cache: false  # Disabled for development
  enable_feature_cache: true
  cache_expiry_hours: 2  # Short expiry for development
  max_cache_size_gb: 1.0  # Smaller cache
  cache_cleanup_threshold: 0.7
  model_load_timeout_s: 120.0
  enable_model_warm_up: false  # Skip warmup for faster startup
  model_precision: "float32"

# Monitoring and Logging
monitoring:
  log_level: "debug"  # Verbose logging for development
  enable_console_logging: true
  enable_file_logging: true
  log_rotation_size_mb: 10  # Smaller log files
  log_backup_count: 3
  system_monitor_interval_s: 10.0
  health_check_interval_s: 60.0
  metrics_export_interval_s: 120.0
  memory_health_threshold: 0.8
  cpu_health_threshold: 0.8
  disk_health_threshold: 0.9
  enable_alerts: false
  alert_cooldown_s: 300

# Physics Features
physics:
  dynamics_thresholds:
    delta_fr_revised: [0.3, 0.7]
    delta_ft_revised: [0.01, 0.05]
    delta_fv_revised: [0.2, 0.5]
  spectral_rolloff_threshold: 0.95
  phase_space_bins: 30  # Fewer bins for faster processing
  phase_space_range: [-2.0, 2.0]
  enable_bessel_analysis: true
  bessel_order_max: 8  # Lower for development
  velocity_smoothing_window: 3
  doppler_frequency_range: [50.0, 8000.0]

# Output Configuration
output_format: "csv"
enable_visualization: true
save_intermediate_results: true  # Helpful for development 